
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 会话补全：messages 全量传入（前端管上下文），返回助手回复文本。
 * 三段式（不持 DB 锁跨 await）：阻塞读配置 → await 网络 → 返回。
 */
async aiChat(messages: ChatMessage[]) : Promise<string> {
    return await TAURI_INVOKE("ai_chat", { messages });
},
async volumeGet() : Promise<VolumeState> {
    return await TAURI_INVOKE("volume_get");
},
async volumeSet(level: number, muted: boolean) : Promise<null> {
    return await TAURI_INVOKE("volume_set", { level, muted });
},
async settingsLoad() : Promise<Settings> {
    return await TAURI_INVOKE("settings_load");
},
async settingsSave(settings: Settings) : Promise<Settings> {
    return await TAURI_INVOKE("settings_save", { settings });
},
async kvGet(key: string) : Promise<string | null> {
    return await TAURI_INVOKE("kv_get", { key });
},
async kvSet(key: string, value: string) : Promise<null> {
    return await TAURI_INVOKE("kv_set", { key, value });
},
async appHealth() : Promise<AppHealth> {
    return await TAURI_INVOKE("app_health");
},
async windowSetPinned(pinned: boolean) : Promise<null> {
    return await TAURI_INVOKE("window_set_pinned", { pinned });
},
async openUrl(url: string) : Promise<null> {
    return await TAURI_INVOKE("open_url", { url });
},
async appList() : Promise<AppEntry[]> {
    return await TAURI_INVOKE("app_list");
},
async appLaunch(appKey: string) : Promise<null> {
    return await TAURI_INVOKE("app_launch", { appKey });
},
/**
 * 拼音/首字母/名称检索（Spotlight 应用路）
 */
async appSearch(query: string, limit: number | null) : Promise<AppEntry[]> {
    return await TAURI_INVOKE("app_search", { query, limit });
},
async todoList() : Promise<Todo[]> {
    return await TAURI_INVOKE("todo_list");
},
async todoCreate(content: string) : Promise<Todo> {
    return await TAURI_INVOKE("todo_create", { content });
},
async todoToggle(id: number, done: boolean) : Promise<null> {
    return await TAURI_INVOKE("todo_toggle", { id, done });
},
async todoDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("todo_delete", { id });
},
async noteList() : Promise<Note[]> {
    return await TAURI_INVOKE("note_list");
},
async noteCreate(content: string) : Promise<Note> {
    return await TAURI_INVOKE("note_create", { content });
},
async noteUpdate(id: number, content: string) : Promise<null> {
    return await TAURI_INVOKE("note_update", { id, content });
},
async noteTogglePin(id: number, pinned: boolean) : Promise<null> {
    return await TAURI_INVOKE("note_toggle_pin", { id, pinned });
},
async noteDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("note_delete", { id });
},
async countdownCustomList() : Promise<CountdownCustom[]> {
    return await TAURI_INVOKE("countdown_custom_list");
},
async countdownCustomCreate(title: string, targetDate: string, emoji: string | null) : Promise<CountdownCustom> {
    return await TAURI_INVOKE("countdown_custom_create", { title, targetDate, emoji });
},
async countdownCustomDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("countdown_custom_delete", { id });
},
async weatherGet() : Promise<WeatherNow> {
    return await TAURI_INVOKE("weather_get");
},
async weatherSetCity(city: string) : Promise<null> {
    return await TAURI_INVOKE("weather_set_city", { city });
},
async countdownList() : Promise<CountdownItem[]> {
    return await TAURI_INVOKE("countdown_list");
},
/**
 * 最近文件（来自文件索引，按修改时间）
 */
async recentFiles(limit: number | null) : Promise<FileHit[]> {
    return await TAURI_INVOKE("recent_files", { limit });
},
/**
 * 常用应用：使用频次 Top N；无使用记录时返回空（前端显示引导态）
 */
async topApps(limit: number | null) : Promise<AppEntry[]> {
    return await TAURI_INVOKE("top_apps", { limit });
},
async systemStats() : Promise<SystemSnapshot> {
    return await TAURI_INVOKE("system_stats");
},
async processList(sort: string | null, limit: number | null) : Promise<ProcInfo[]> {
    return await TAURI_INVOKE("process_list", { sort, limit });
},
async processKill(pid: number) : Promise<null> {
    return await TAURI_INVOKE("process_kill", { pid });
},
async fileSearch(query: string, limit: number | null) : Promise<FileHit[]> {
    return await TAURI_INVOKE("file_search", { query, limit });
},
/**
 * 手动触发全量重扫（后台线程，完成发 FileIndexUpdated 事件）
 */
async fileIndexRefresh() : Promise<null> {
    return await TAURI_INVOKE("file_index_refresh");
},
/**
 * 打开文件（须位于索引根目录内，SDD §8 白名单）
 */
async openPath(path: string) : Promise<null> {
    return await TAURI_INVOKE("open_path", { path });
},
/**
 * 在资源管理器中定位
 */
async revealInExplorer(path: string) : Promise<null> {
    return await TAURI_INVOKE("reveal_in_explorer", { path });
},
async desktopModeEnter() : Promise<null> {
    return await TAURI_INVOKE("desktop_mode_enter");
},
async desktopModeExit() : Promise<null> {
    return await TAURI_INVOKE("desktop_mode_exit");
},
async desktopModeIsActive() : Promise<boolean> {
    return await TAURI_INVOKE("desktop_mode_is_active");
},
/**
 * 唤出系统真实「开始」菜单（注入 Ctrl+Esc，见 hamster_platform::shell）
 */
async startMenuOpen() : Promise<null> {
    return await TAURI_INVOKE("start_menu_open");
},
async benchScanAgents() : Promise<AgentInfo[]> {
    return await TAURI_INVOKE("bench_scan_agents");
},
async benchListProjects() : Promise<string[]> {
    return await TAURI_INVOKE("bench_list_projects");
},
/**
 * 聚合各已安装 Agent 的历史工作目录（读会话记录的 cwd，Store 为空时的项目来源）。
 * 只保留磁盘上仍存在的目录，并跳过临时目录（e2e 沙箱会污染 ~/.claude/projects 等）。
 */
async benchAgentWorkspaces() : Promise<WorkspaceRecord[]> {
    return await TAURI_INVOKE("bench_agent_workspaces");
},
/**
 * 创建流式会话（官方 headless 协议）。事件经 BenchStreamEvent 推送；
 * first_prompt 非空时握手后立即发起首轮。
 */
async benchStreamCreate(agentId: string, projectDir: string, firstPrompt: string | null, model: string | null, effort: string | null, resumeKey: string | null, fork: boolean) : Promise<LiveSessionInfo> {
    return await TAURI_INVOKE("bench_stream_create", { agentId, projectDir, firstPrompt, model, effort, resumeKey, fork });
},
async benchStreamSend(sessionId: string, text: string, model: string | null, effort: string | null) : Promise<null> {
    return await TAURI_INVOKE("bench_stream_send", { sessionId, text, model, effort });
},
async benchStreamInterrupt(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("bench_stream_interrupt", { sessionId });
},
async benchStreamKill(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("bench_stream_kill", { sessionId });
},
async benchListStreamSessions() : Promise<LiveSessionInfo[]> {
    return await TAURI_INVOKE("bench_list_stream_sessions");
},
/**
 * PTY 活会话（与流式列表并存；侧栏合并去重）
 */
async benchListLiveSessions() : Promise<LiveSessionInfo[]> {
    return await TAURI_INVOKE("bench_list_live_sessions");
},
/**
 * 创建 PTY 会话（官方 CLI TUI + 官方 resume 参数）。输出经 ipc Channel 推送；
 * GUI 输入框的文字走 bench_pty_send_prompt（bracketed-paste 注入 stdin）。
 */
async benchPtyCreate(args: PtyCreateArgs, onData: TAURI_CHANNEL<number[]>) : Promise<LiveSessionInfo> {
    return await TAURI_INVOKE("bench_pty_create", { args, onData });
},
async benchPtyWrite(sessionId: string, data: string) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_write", { sessionId, data });
},
/**
 * GUI 输入通道：文本以 bracketed-paste 注入运行中会话（混用模式，上游设计文档 runtime-design §3.6）
 */
async benchPtySendPrompt(sessionId: string, text: string) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_send_prompt", { sessionId, text });
},
async benchPtyResize(sessionId: string, cols: number, rows: number) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_resize", { sessionId, cols, rows });
},
async benchPtyKill(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_kill", { sessionId });
},
async benchListHistorySessions() : Promise<SessionSummary[]> {
    return await TAURI_INVOKE("bench_list_history_sessions");
},
/**
 * 检索前触发一轮快速增量摄取（未变更文件仅 stat + 游标比对，短暂阻塞可接受——
 * 与上游同款：async 命令体内直调 rusqlite，State 借用不跨 spawn）
 */
async benchSearchSessions(query: SearchQuery) : Promise<SearchHit[]> {
    return await TAURI_INVOKE("bench_search_sessions", { query });
},
async benchSessionMessages(agent: string, sessionKey: string, aroundSeq: number, window: number) : Promise<SnapshotMessage[]> {
    return await TAURI_INVOKE("bench_session_messages", { agent, sessionKey, aroundSeq, window });
},
async benchListSessionMessages(agent: string, sessionKey: string, fromSeq: number, limit: number) : Promise<SessionMessagesPage> {
    return await TAURI_INVOKE("bench_list_session_messages", { agent, sessionKey, fromSeq, limit });
},
/**
 * 某代理在项目下最新入索引的会话键（登记表条目缺 sessionKey 时的恢复回退）
 */
async benchLatestIndexedSession(agent: string, projectDir: string) : Promise<SessionSummary | null> {
    return await TAURI_INVOKE("bench_latest_indexed_session", { agent, projectDir });
},
async benchIndexStatus() : Promise<IndexStatus> {
    return await TAURI_INVOKE("bench_index_status");
},
async benchIndexRefresh() : Promise<IndexStatus> {
    return await TAURI_INVOKE("bench_index_refresh");
},
async benchReindex() : Promise<IndexStatus> {
    return await TAURI_INVOKE("bench_reindex");
},
/**
 * 删除一条历史会话：备份源文件（上游红线②，备份后删）→ 删除 → 清索引派生数据
 */
async benchSessionDelete(agent: string, sessionKey: string) : Promise<null> {
    return await TAURI_INVOKE("bench_session_delete", { agent, sessionKey });
},
/**
 * 创建桌面助手会话：解析默认代理 → 铸造令牌 → 注入 HTTP MCP 配置 → spawn。
 */
async benchAssistantCreate(args: AssistantCreateArgs) : Promise<AssistantSessionInfo> {
    return await TAURI_INVOKE("bench_assistant_create", { args });
},
/**
 * 各 agent 的桌面 MCP 分发状态
 */
async agentMcpStatus() : Promise<AgentMcpStatus[]> {
    return await TAURI_INVOKE("agent_mcp_status");
},
/**
 * 开/关某 agent 的桌面 MCP 分发：
 * 开 = 源 upsert（HTTP IR）+ target 启用 → plan/apply 写入其配置文件；
 * 关 = 源临时置 disabled → 仅对该 target apply（渲染省略 = 摘除条目）→ 恢复源。
 * Drift（基线外的既有配置）统一 Overwrite：render 本身「读现有→合并」，
 * 用户已有条目保留，apply 自动落备份可回滚。
 */
async agentMcpSetEnabled(agentId: string, enabled: boolean) : Promise<null> {
    return await TAURI_INVOKE("agent_mcp_set_enabled", { agentId, enabled });
},
/**
 * 接入信息（URL 含实际端口；端口回退时前端提示更新已分发配置）
 */
async agentMcpAccessInfo() : Promise<McpAccessInfo> {
    return await TAURI_INVOKE("agent_mcp_access_info");
},
/**
 * 扫描插件列表
 */
async pluginList() : Promise<PluginInfo[]> {
    return await TAURI_INVOKE("plugin_list");
},
/**
 * 读取插件入口代码（前端 blob 动态 import 用）
 */
async pluginReadCode(pluginId: string, entry: string) : Promise<string> {
    return await TAURI_INVOKE("plugin_read_code", { pluginId, entry });
},
/**
 * 插件私有存储读（settings 表 `plugin.<id>.<key>` 命名空间）
 */
async pluginStorageGet(pluginId: string, key: string) : Promise<string | null> {
    return await TAURI_INVOKE("plugin_storage_get", { pluginId, key });
},
/**
 * 插件私有存储写
 */
async pluginStorageSet(pluginId: string, key: string, value: string) : Promise<null> {
    return await TAURI_INVOKE("plugin_storage_set", { pluginId, key, value });
},
/**
 * 插件删除：整目录移除（防路径逃逸）
 */
async pluginDelete(pluginId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin_delete", { pluginId });
},
/**
 * 受控桥：插件经 manifest 声明的权限调用有限的桌面能力。
 * 返回 JSON 字符串（能力各自定义返回形态）。
 */
async pluginBridgeCall(pluginId: string, capability: string, payload: string) : Promise<string> {
    return await TAURI_INVOKE("plugin_bridge_call", { pluginId, capability, payload });
},
/**
 * 打开原生托盘溢出弹层（系统自带 UI，含全部后台托盘 app，可直接交互）。
 * 
 * 借壳显示系统任务栏的 ~1s 里先把 dock 切成不透明（见 [`OpaqueDockGuard`]），
 * 配合 open_overflow 内的置顶压制，全程看不到任务栏闪现，dock 不再「上浮」。
 */
async trayOpenOverflow() : Promise<null> {
    return await TAURI_INVOKE("tray_open_overflow");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appIndexUpdated: AppIndexUpdated,
benchPtyExit: BenchPtyExit,
benchStreamEvent: BenchStreamEvent,
benchStreamExit: BenchStreamExit,
coreReady: CoreReady,
desktopModeChanged: DesktopModeChanged,
fileIndexUpdated: FileIndexUpdated
}>({
appIndexUpdated: "app-index-updated",
benchPtyExit: "bench-pty-exit",
benchStreamEvent: "bench-stream-event",
benchStreamExit: "bench-stream-exit",
coreReady: "core-ready",
desktopModeChanged: "desktop-mode-changed",
fileIndexUpdated: "file-index-updated"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Agent 域设置：桌面助手 persona、computer use 安全开关与桌面 MCP 分发
 */
export type Agent = { 
/**
 * computer use 总开关：允许 agent 经桌面 MCP server 操作真实鼠标键盘
 * （HAMSTER_CU_MODE 注入；默认关，安全红线见 docs/03 §3.4）
 */
computer_use_enabled: boolean; 
/**
 * 桌面助手 persona（追加为 agent system prompt；空 = 内置仓鼠默认）
 */
assistant_persona: string; 
/**
 * 桌面 MCP 端口（None = 默认 47613；被占用时回退随机端口，实际值见设置页）
 */
mcp_port: number | null; 
/**
 * 用户级长效令牌：写入各 agent 配置文件供外部 MCP 宿主接入
 * （None = 首启自动生成；区别于 bench 助手会话的一次性令牌）
 */
mcp_user_token: string | null; 
/**
 * 已开启桌面 MCP 分发的 agent id（写入其配置文件；移除 = 从配置摘除条目）
 */
mcp_agents: string[]; 
/**
 * 桌面助手默认代理（空 = 自动：claude → zcode → 首个已装且支持结构化通道）
 */
assistant_agent_id: string; 
/**
 * 桌面助手默认模型（空 = agent CLI 自身默认）
 */
assistant_model: string; 
/**
 * 桌面助手默认推理强度（空 = agent 默认；选项来自各 agent launchOptions）
 */
assistant_effort: string }
/**
 * 扫描结果（前端展示形态）。
 */
export type AgentInfo = { id: string; name: string; installed: boolean; version: string | null; 
/**
 * 配置根路径（未安装为 null）
 */
configRoot: string | null; capabilities: Caps; 
/**
 * 支持内嵌对话（v2.0：adapter 提供 runtime 画像）
 */
chat: boolean; 
/**
 * 首条 prompt 注入方式；None = 不支持自动注入（消息不会随启动送达）
 */
promptInject: PromptInject | null; 
/**
 * 启动可选参数（模型/推理强度，官方 CLI 参数）；None = 不支持内嵌对话
 */
launchOptions: LaunchOptions | null; 
/**
 * 支持官方结构化流式通道（v2.0 R3：GUI 会话实时渲染）
 */
streaming: boolean }
/**
 * 分发状态（agent_mcp_status 返回项）
 */
export type AgentMcpStatus = { agentId: string; agentName: string; installed: boolean; 
/**
 * 该 agent 是否支持 MCP 配置分发
 */
mcpCapable: boolean; 
/**
 * 用户开关（settings.agent.mcp_agents）
 */
enabled: boolean; 
/**
 * 配置文件路径（mcp 不可用为空串）
 */
configPath: string }
export type Ai = { base_url: string; model: string; api_key: string | null }
export type AppEntry = { app_key: string; display_name: string; 
/**
 * 启动目标：.lnk 完整路径（ShellExecute 直接打开）
 */
exec_target: string; kind: string; 
/**
 * 图标 PNG 缓存路径（None = 前端用字母占位）
 */
icon_path: string | null }
export type AppError = { code: string; message: string }
export type AppHealth = { name: string; version: string }
export type AppIndexUpdated = { count: number }
export type Appearance = { theme: string; accent: string; glass: string; font_scale: number }
/**
 * bench_assistant_create 参数包
 */
export type AssistantCreateArgs = { firstPrompt: string | null; model: string | null; 
/**
 * 推理强度（结构化通道原生支持；None = 用设置默认）
 */
effort: string | null; 
/**
 * 指定代理；缺省按 设置默认 → claude → zcode → 首个已装 顺序解析
 */
agentId: string | null }
/**
 * 桌面助手会话信息（返回给前端；附注入摘要便于调试与展示）
 */
export type AssistantSessionInfo = { session: LiveSessionInfo; agentId: string; 
/**
 * 本会话是否注入了桌面 MCP server
 */
mcpInjected: boolean; 
/**
 * 本会话 computer use 是否放行（未放行时 computer_* 工具被 server 拒绝）
 */
computerUseEnabled: boolean }
export type Behavior = { autostart: boolean; start_minimized: boolean; language: string; 
/**
 * 桌面模式切换热键（tauri global-shortcut 格式，重启生效）
 */
desktop_mode_hotkey: string; 
/**
 * 启动即进入桌面模式（对齐水豚hub：打开应用直接全屏工作台 + 底部 Dock）
 */
desktop_mode_on_launch: boolean }
/**
 * PTY 会话进程退出（TUI 会话）
 */
export type BenchPtyExit = { session_id: string; exit_code: number }
/**
 * 流式会话事件（GUI 对话数据源；payload 为 上游 归一化 StreamEvent）
 */
export type BenchStreamEvent = StreamEvent
/**
 * 流式会话进程退出（前端刷新活会话列表）
 */
export type BenchStreamExit = { session_id: string }
/**
 * Agent 能力声明。Adapter 必须如实声明，不夸大。
 */
export type Caps = { 
/**
 * 支持用户级 MCP 分发
 */
mcp: boolean; 
/**
 * 支持项目级 MCP（scope = Project）
 */
projectMcp: boolean; 
/**
 * 规则文件分发（M1）
 */
rules: boolean; 
/**
 * Skills 目录管理（M1）
 */
skills: boolean; 
/**
 * 工具颗粒度（v1.2）：支持把 disabledTools 分发为工具级权限规则
 */
toolGranularity: boolean }
export type ChatMessage = { role: string; content: string }
export type CoreReady = { version: string }
export type CountdownCustom = { id: number; title: string; target_date: string; emoji: string }
export type CountdownItem = { title: string; days: number; 
/**
 * auto = 内置计算项；custom = 用户自建
 */
kind: string; emoji: string }
export type CpuStat = { percent: number; core_count: number; name: string }
export type DesktopModeChanged = { active: boolean }
export type DiskStat = { 
/**
 * 挂载点，如 "C:\"
 */
mount: string; total_gb: number; used_gb: number; percent: number }
export type FileHit = { path: string; name: string; ext: string | null; kind: string; size: number; mtime: number }
export type FileIndex = { roots: string[]; max_files: number }
export type FileIndexUpdated = { count: number }
/**
 * 索引库状态（Settings / Doctor 展示）。
 */
export type IndexStatus = { sessions: number; messages: number; 
/**
 * 库文件体积（字节）
 */
bytes: number }
/**
 * 一个启动选项的声明（choices 供前端下拉，arg_template 是含 {v} 占位符的
 * 官方参数模板，可含多个 token，spawn 前按空格拆分）。
 */
export type LaunchOption = { choices: string[]; argTemplate: string; default: string | null; 
/**
 * 选择的值在 GUI 流式会话同样生效（claude 启动 flag / codex turn 参数）；
 * false = 仅 TUI 会话生效（如 opencode：TUI `--model`，其 ACP 通道
 * 无启动级模型参数、`session/set_config` 上游未实现）
 */
streamOverride: boolean }
/**
 * 前端可选的启动参数组合（供 AgentInfo 能力暴露）。
 */
export type LaunchOptions = { model: LaunchOption | null; effort: LaunchOption | null }
/**
 * 活会话信息（前端 Chat 左栏 / 上下文条的数据形态）。
 */
export type LiveSessionInfo = { 
/**
 * 上游 侧会话 id（uuid）
 */
sessionId: string; agentId: string; 
/**
 * 会话形态（Agent 对话 / 通用终端）；终端会话不进 Chat 侧栏
 */
kind: SessionKind; 
/**
 * 通道：PTY TUI 或结构化流式（原生视图据此分流数据源）
 */
channel: SessionChannel; projectDir: string; 
/**
 * 会话是否仍在运行（false 时 exit_code 有效）
 */
running: boolean; exitCode: number | null; 
/**
 * Unix 毫秒时间戳
 */
startedAt: number; 
/**
 * 最近一次输入/输出的时刻（用于排序）
 */
lastActiveAt: number; 
/**
 * rollout 会话键（resume 启动时记录）：侧栏按会话聚合 + spawn 幂等裁决
 */
resumeKey?: string | null }
/**
 * 接入信息（设置页展示 + 供手动复制到任意 MCP 宿主）
 */
export type McpAccessInfo = { url: string; token: string; port: number; 
/**
 * 端口回退过（首选端口被占用，分发出去的固定 URL 当前不可用）
 */
portFellBack: boolean; defaultPort: number }
export type MemStat = { total_gb: number; used_gb: number; percent: number }
export type Note = { id: number; content: string; pinned: boolean; updated_at: number }
/**
 * 插件信息（命令返回；不含代码）
 */
export type PluginInfo = { id: string; name: string; version: string; description: string; author: string; entry: string; 
/**
 * 声明式权限（透传给前端构建 ctx.api）
 */
permissions: string[]; 
/**
 * 入口文件完整路径（前端据此请求代码）
 */
entryPath: string }
export type ProcInfo = { pid: number; name: string; mem_mb: number; cpu: number }
/**
 * 首条 prompt 送达方式（runtime-design.md §3.4）。
 */
export type PromptInject = 
/**
 * 作为位置参数拼进启动 argv（`claude "消息"`）
 */
"argv" | 
/**
 * 先开终端，用户自己在 TUI 内输入（上游 不注入）
 */
"none"
/**
 * bench_pty_create 参数包（specta 的 SpectaFn 上限 10 参，命令参数打包）
 */
export type PtyCreateArgs = { agentId: string; projectDir: string; firstPrompt: string | null; model: string | null; effort: string | null; resumeKey: string | null; cols: number; rows: number }
export type Search = { hotkey: string; search_apps: boolean; search_files: boolean }
/**
 * 一条全文命中（消息级定位）。
 */
export type SearchHit = { agent: string; sessionKey: string; seq: number; sessionTitle: string; projectPath: string | null; at: number | null; 
/**
 * 命中上下文片段（带标记）
 */
snippet: string }
/**
 * 全文检索查询（agents 为空 = 不过滤）。
 */
export type SearchQuery = { text: string; agents: string[]; project: string | null; limit: number | null }
/**
 * 会话通道形态：PTY 内嵌 TUI，或官方结构化协议流式（v2.0 R3）。
 */
export type SessionChannel = "pty" | "stream"
/**
 * 会话形态：Agent TUI 对话（Chat 域主体）或工作台通用终端（底部 dock，
 * git/构建等日常 shell，不属于任何 Agent）。
 */
export type SessionKind = "agent" | "terminal"
/**
 * 原生视图分页：会话消息总数 + 从 from_seq 起的升序消息。
 */
export type SessionMessagesPage = { total: number; messages: SnapshotMessage[] }
/**
 * 一条历史会话的摘要（从 Agent 官方落盘文件只读提取）。
 */
export type SessionSummary = { 
/**
 * Agent 全小写 id（"claude" / "codex" / …）
 */
agent: string; 
/**
 * Agent 侧会话标识（resume 用，如 Claude 的 uuid）
 */
sessionKey: string; 
/**
 * 会话所属项目目录（Agent 落盘的 cwd）
 */
projectPath: string; 
/**
 * 标题（首条用户消息截断；提取不到时为空，由前端兜底）
 */
title: string; 
/**
 * 最近活跃时刻（Unix 毫秒，取文件 mtime）
 */
lastActiveAt: number; 
/**
 * 源文件路径（只读回指，调试与排重用）
 */
sourcePath: string; 
/**
 * 是否已声明官方 resume 参数（false = 仅浏览，UI 不提供续聊）
 */
resumable: boolean; 
/**
 * 续聊须走 TUI（PTY）通道：GUI 流式协议 resume 该会话必失败
 * （如 codex rollout 引用当前配置无法解析的 model provider，实测 0.152.0）
 */
resumeViaTui?: boolean }
export type Settings = { appearance: Appearance; search: Search; file_index: FileIndex; weather: Weather; ai: Ai; behavior: Behavior; 
/**
 * Agent 域（桌面助手 / computer use，M4）
 */
agent: Agent }
/**
 * 一条可检索的消息投影（原文仍在 Agent 源文件，索引只存文本投影）。
 */
export type SnapshotMessage = { 
/**
 * 所在源文件的行号（0 基），作为会话内稳定序号
 */
seq: number; role: SnapshotRole; 
/**
 * 提取的纯文本（搜索面）
 */
text: string; toolName: string | null; at: number | null }
/**
 * 消息角色（索引投影用，保持最小集合）。
 */
export type SnapshotRole = "user" | "assistant" | 
/**
 * 思考/推理内容（默认折叠展示）
 */
"thinking" | "tool" | "system"
/**
 * 归一化流式事件（方言无关；前端据此增量渲染原生视图）。
 */
export type StreamEvent = { sessionId: string; 
/**
 * 方言侧条目 id（增量拼接的去重键；无条目语义的事件为空）
 */
itemId: string; at: number; kind: StreamEventKind; 
/**
 * 文本增量 / 条目全文（按 kind 语义）
 */
text: string; 
/**
 * 工具类条目的名称（command 首词 / server.tool）
 */
toolName: string | null; 
/**
 * 工具条目状态（completed/failed/inProgress…，方言原样透传）
 */
status: string | null; 
/**
 * 结构化文件修改（仅 ToolItem 且方言提供时；前端渲染 diff 卡片）
 */
diff?: StreamEventDiff | null }
/**
 * 工具条目的结构化 diff（ACP `tool_call` 的 `content[].type=diff`；其余方言/情形为 None）。
 */
export type StreamEventDiff = { path: string; oldText: string | null; newText: string }
export type StreamEventKind = 
/**
 * 用户消息回显（权威全文）
 */
"userEcho" | 
/**
 * 助手消息增量（append）
 */
"agentDelta" | 
/**
 * 助手消息完成（权威全文，替换该条目）
 */
"agentDone" | 
/**
 * 思考增量（append）
 */
"reasoningDelta" | 
/**
 * 条目完成：工具调用（command/fileChange/mcpToolCall…）
 */
"toolItem" | 
/**
 * 条目完成：思考全文
 */
"reasoningDone" | 
/**
 * 轮次开始（输入已被接受）
 */
"turnStarted" | 
/**
 * 轮次完成（running=false）
 */
"turnCompleted" | 
/**
 * 协议错误 / 会话错误
 */
"error" | 
/**
 * 通道进程退出
 */
"exit"
export type SystemSnapshot = { mem: MemStat; disks: DiskStat[]; cpu: CpuStat; 
/**
 * Windows 上常为空（依赖传感器驱动），前端按空隐藏
 */
temps: TempStat[] }
export type TempStat = { label: string; celsius: number }
export type Todo = { id: number; content: string; done: boolean; created_at: number }
export type VolumeState = { 
/**
 * 0.0 - 1.0
 */
level: number; muted: boolean }
export type Weather = { provider: string; city_id: string; qweather_key: string | null }
export type WeatherNow = { city: string; temp: number; kind: string; emoji: string; temp_min: number; temp_max: number; 
/**
 * 缓存时间（unix 秒）；0 = 实时
 */
fetched_at: number }
/**
 * 一条 workspace 记录。
 */
export type WorkspaceRecord = { dir: string; 
/**
 * 发现来源描述（展示用），如 "claude projects" / "codex sessions" / "zcode recentProjects"
 */
source: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
