
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 会话补全：messages 全量传入（前端管上下文），返回助手回复文本。
 * 三段式（不持 DB 锁跨 await）：阻塞读配置 → await 网络 → 返回。
 */
async aiChat(messages: ChatMessage[]) : Promise<string> {
    return await TAURI_INVOKE("ai_chat", { messages });
},
async volumeGet() : Promise<VolumeState> {
    return await TAURI_INVOKE("volume_get");
},
async volumeSet(level: number, muted: boolean) : Promise<null> {
    return await TAURI_INVOKE("volume_set", { level, muted });
},
async settingsLoad() : Promise<Settings> {
    return await TAURI_INVOKE("settings_load");
},
async settingsSave(settings: Settings) : Promise<Settings> {
    return await TAURI_INVOKE("settings_save", { settings });
},
/**
 * 手动指定 Agent CLI 程序路径（设置 → Agent；绿色版/自拷贝 CLI 未上 PATH 时用）。
 * 先校验再落库：agent id 必须在注册表内、路径必须是存在的文件；`path = None` 清除。
 * 生效点：扫描（installed/program）与启动（覆盖自动探测的最高版本结果）。
 */
async agentCliPathSet(agentId: string, path: string | null) : Promise<Partial<{ [key in string]: string }>> {
    return await TAURI_INVOKE("agent_cli_path_set", { agentId, path });
},
async kvGet(key: string) : Promise<string | null> {
    return await TAURI_INVOKE("kv_get", { key });
},
async kvSet(key: string, value: string) : Promise<null> {
    return await TAURI_INVOKE("kv_set", { key, value });
},
async appHealth() : Promise<AppHealth> {
    return await TAURI_INVOKE("app_health");
},
async windowSetPinned(pinned: boolean) : Promise<null> {
    return await TAURI_INVOKE("window_set_pinned", { pinned });
},
async openUrl(url: string) : Promise<null> {
    return await TAURI_INVOKE("open_url", { url });
},
/**
 * 导入自定义主屏壁纸：校验图片扩展名 → 拷贝进 app_data_dir/wallpapers →
 * 返回新文件的绝对路径（前端存入 home.layout.wallpaperImage，经 asset
 * protocol 显示）。previous 传上一张自定义壁纸路径，仅在 wallpapers
 * 目录内才会被删除，避免误删用户目录里的原图。
 */
async wallpaperImageImport(path: string, previous: string | null) : Promise<string> {
    return await TAURI_INVOKE("wallpaper_image_import", { path, previous });
},
async appList() : Promise<AppEntry[]> {
    return await TAURI_INVOKE("app_list");
},
async appLaunch(appKey: string) : Promise<null> {
    return await TAURI_INVOKE("app_launch", { appKey });
},
/**
 * 多开：绕过「已运行激活现有窗口」，直接 shell_open 再开一个。
 * 文件夹/记事本/浏览器得到新窗口；单实例应用由其自身去重（等效激活）。
 * 顺带自学习多开能力：已存在窗口时再开、1.5s 后窗数没涨 → 记为单实例，
 * 菜单不再提供「多开」；涨了 → 移出名单重新放行（见 app_multi_flags）。
 */
async appLaunchNew(appKey: string) : Promise<null> {
    return await TAURI_INVOKE("app_launch_new", { appKey });
},
/**
 * 查询 keys 中已知不支持多开的应用（内置名单 + 运行时自学习并集），
 * 菜单据此隐藏「多开应用」项。
 */
async appMultiFlags(keys: string[]) : Promise<string[]> {
    return await TAURI_INVOKE("app_multi_flags", { keys });
},
/**
 * 枚举应用的全部可见顶层窗口（z 序，最上层在前）——dock 悬停卡片用。
 * 解析不出 exe（UWP/文件夹）返回空表。
 */
async appWindows(appKey: string) : Promise<AppWindowInfo[]> {
    return await TAURI_INVOKE("app_windows", { appKey });
},
/**
 * 前置（必要时还原）指定窗口——dock 悬停卡片点选目标窗口
 */
async appWindowActivate(id: number) : Promise<null> {
    return await TAURI_INVOKE("app_window_activate", { id });
},
/**
 * 关闭单扇窗口（dock 悬停卡片行 X）：对该 hwnd 投递 WM_CLOSE 温和关闭
 */
async appWindowClose(id: number) : Promise<null> {
    return await TAURI_INVOKE("app_window_close", { id });
},
/**
 * 关闭应用：对其 exe 名下全部可见窗口投递 WM_CLOSE（温和关闭，应用可弹
 * 保存确认）。解析不出 exe（UWP/文件夹）或没有可见窗口时报错。
 */
async appClose(appKey: string) : Promise<null> {
    return await TAURI_INVOKE("app_close", { appKey });
},
/**
 * dock 运行态轮询：返回 keys 中当前有可见窗口的应用 app_key。
 * DB 查询留在调用线程（毫秒级）；lnk 解析 + EnumWindows 放线程池，不占主线程。
 */
async appsRunning(keys: string[]) : Promise<string[]> {
    return await TAURI_INVOKE("apps_running", { keys });
},
/**
 * 拼音/首字母/名称检索（Spotlight 应用路）
 */
async appSearch(query: string, limit: number | null) : Promise<AppEntry[]> {
    return await TAURI_INVOKE("app_search", { query, limit });
},
/**
 * 分屏会话快照。读的时候会自愈：已被关掉的窗口剔除、剩下的按新成员数补位。
 */
async splitState() : Promise<SplitState> {
    return await TAURI_INVOKE("split_state");
},
/**
 * 把应用的一扇窗口加入分屏（同一应用多次调用依次加入它的多扇窗口）。
 * 首次调用即建立会话；已满 4 扇或该应用没有可分屏的窗口时报错（前端据此提示）。
 */
async splitAdd(appKey: string) : Promise<SplitState> {
    return await TAURI_INVOKE("split_add", { appKey });
},
/**
 * 把某扇窗口移出分屏：它回到加入前的位置/状态，剩下的补位。
 * （「关闭窗口」是另一回事，前端调 app_window_close + split_state 补位。）
 */
async splitRemove(windowId: number) : Promise<SplitState> {
    return await TAURI_INVOKE("split_remove", { windowId });
},
/**
 * 退出分屏：全部窗口回到加入前的位置与显示状态。
 */
async splitExit() : Promise<SplitState> {
    return await TAURI_INVOKE("split_exit");
},
/**
 * 打开（或换目标重开）dock 弹窗：水平钳进任务栏范围，垂直落在任务栏条
 * 上沿上方 8px。menu/split 抢焦点（失焦即收）；hover 不抢焦点（跟随悬停）。
 */
async dockMenuOpen(payload: DockMenuPayload) : Promise<null> {
    return await TAURI_INVOKE("dock_menu_open", { payload });
},
/**
 * 弹窗挂载时拉取当前载荷（之后靠 payload 事件增量更新）
 */
async dockMenuPayload() : Promise<DockMenuPayload | null> {
    return await TAURI_INVOKE("dock_menu_payload");
},
/**
 * 收回弹窗（失焦/Esc/动作完成/退出桌面模式/悬停离开）
 */
async dockMenuHide() : Promise<null> {
    return await TAURI_INVOKE("dock_menu_hide");
},
/**
 * 打开「管理分屏」弹层（任务栏胶囊点击）：与右键菜单同一置顶小窗，
 * 只是 kind=split、尺寸按成员行数算（行数由调用方给，避免弹窗自己再查一遍会话）。
 */
async splitMenuOpen(x: number, count: number) : Promise<null> {
    return await TAURI_INVOKE("split_menu_open", { x, count });
},
async todoList() : Promise<Todo[]> {
    return await TAURI_INVOKE("todo_list");
},
async todoCreate(content: string, dueAt: number | null, remind: boolean | null) : Promise<Todo> {
    return await TAURI_INVOKE("todo_create", { content, dueAt, remind });
},
async todoToggle(id: number, done: boolean) : Promise<null> {
    return await TAURI_INVOKE("todo_toggle", { id, done });
},
async todoDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("todo_delete", { id });
},
async todoSetDue(id: number, dueAt: number | null, remind: boolean) : Promise<Todo> {
    return await TAURI_INVOKE("todo_set_due", { id, dueAt, remind });
},
async todoSetRecur(id: number, recur: string | null) : Promise<Todo> {
    return await TAURI_INVOKE("todo_set_recur", { id, recur });
},
async vaultStatus() : Promise<VaultStatus> {
    return await TAURI_INVOKE("vault_status");
},
/**
 * 首次创建密码库：生成 KDF 参数与 verifier，解锁会话
 */
async vaultSetup(password: string, hint: string | null, autoLockSecs: number | null) : Promise<VaultStatus> {
    return await TAURI_INVOKE("vault_setup", { password, hint, autoLockSecs });
},
async vaultUnlock(password: string) : Promise<VaultStatus> {
    return await TAURI_INVOKE("vault_unlock", { password });
},
async vaultLock() : Promise<VaultStatus> {
    return await TAURI_INVOKE("vault_lock");
},
async vaultSetAutoLock(secs: number) : Promise<VaultStatus> {
    return await TAURI_INVOKE("vault_set_auto_lock", { secs });
},
/**
 * 换主密码：校验旧密码 → 全量重加密 → 轮换 KDF 参数与 verifier
 */
async vaultChangePassword(oldPassword: string, newPassword: string, hint: string | null) : Promise<VaultStatus> {
    return await TAURI_INVOKE("vault_change_password", { oldPassword, newPassword, hint });
},
async vaultItemList() : Promise<VaultItem[]> {
    return await TAURI_INVOKE("vault_item_list");
},
async vaultItemSearch(query: string) : Promise<VaultItem[]> {
    return await TAURI_INVOKE("vault_item_search", { query });
},
async vaultItemCreate(input: VaultItemInput) : Promise<VaultItem> {
    return await TAURI_INVOKE("vault_item_create", { input });
},
async vaultItemUpdate(id: number, input: VaultItemInput) : Promise<VaultItem> {
    return await TAURI_INVOKE("vault_item_update", { id, input });
},
async vaultItemToggleFavorite(id: number, favorite: boolean) : Promise<VaultItem> {
    return await TAURI_INVOKE("vault_item_toggle_favorite", { id, favorite });
},
/**
 * 软删除（回收站 M2 展示）
 */
async vaultItemDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("vault_item_delete", { id });
},
/**
 * 取某条敏感字段（唯一取密口；UI 显式点击才调用）
 */
async vaultItemReveal(id: number) : Promise<VaultSecret> {
    return await TAURI_INVOKE("vault_item_reveal", { id });
},
/**
 * 复制字段到剪贴板（Rust 侧写入；密码在 CLIPBOARD_CLEAR_SECS 后自动清除，
 * 仅当剪贴板内容仍是本次写入时才清，避免误伤用户后续复制）
 */
async vaultCopyField(id: number, field: string) : Promise<number> {
    return await TAURI_INVOKE("vault_copy_field", { id, field });
},
async vaultPasswordGenerate(options: GenOptions) : Promise<string> {
    return await TAURI_INVOKE("vault_password_generate", { options });
},
async vaultPasswordStrength(password: string) : Promise<number> {
    return await TAURI_INVOKE("vault_password_strength", { password });
},
async focusStart(minutes: number, todoId: number | null) : Promise<FocusStatus> {
    return await TAURI_INVOKE("focus_start", { minutes, todoId });
},
async focusBreak(minutes: number) : Promise<FocusStatus> {
    return await TAURI_INVOKE("focus_break", { minutes });
},
async focusPause() : Promise<null> {
    return await TAURI_INVOKE("focus_pause");
},
async focusResume() : Promise<null> {
    return await TAURI_INVOKE("focus_resume");
},
async focusStop() : Promise<null> {
    return await TAURI_INVOKE("focus_stop");
},
async focusStatus() : Promise<FocusStatus | null> {
    return await TAURI_INVOKE("focus_status");
},
async focusHistory(days: number | null) : Promise<FocusDayStat[]> {
    return await TAURI_INVOKE("focus_history", { days });
},
async noteList() : Promise<Note[]> {
    return await TAURI_INVOKE("note_list");
},
async noteCreate(content: string) : Promise<Note> {
    return await TAURI_INVOKE("note_create", { content });
},
async noteUpdate(id: number, content: string) : Promise<null> {
    return await TAURI_INVOKE("note_update", { id, content });
},
async noteTogglePin(id: number, pinned: boolean) : Promise<null> {
    return await TAURI_INVOKE("note_toggle_pin", { id, pinned });
},
async noteDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("note_delete", { id });
},
async countdownCustomList() : Promise<CountdownCustom[]> {
    return await TAURI_INVOKE("countdown_custom_list");
},
async countdownCustomCreate(title: string, targetDate: string, emoji: string | null) : Promise<CountdownCustom> {
    return await TAURI_INVOKE("countdown_custom_create", { title, targetDate, emoji });
},
async countdownCustomDelete(id: number) : Promise<null> {
    return await TAURI_INVOKE("countdown_custom_delete", { id });
},
async weatherGet() : Promise<WeatherNow> {
    return await TAURI_INVOKE("weather_get");
},
async weatherSetCity(city: string) : Promise<null> {
    return await TAURI_INVOKE("weather_set_city", { city });
},
async countdownList() : Promise<CountdownItem[]> {
    return await TAURI_INVOKE("countdown_list");
},
/**
 * 最近文件（来自文件索引，按修改时间）
 */
async recentFiles(limit: number | null) : Promise<FileHit[]> {
    return await TAURI_INVOKE("recent_files", { limit });
},
/**
 * 常用应用：使用频次 Top N；无使用记录时返回空（前端显示引导态）
 */
async topApps(limit: number | null) : Promise<AppEntry[]> {
    return await TAURI_INVOKE("top_apps", { limit });
},
async systemStats() : Promise<SystemSnapshot> {
    return await TAURI_INVOKE("system_stats");
},
async processList(sort: string | null, limit: number | null) : Promise<ProcInfo[]> {
    return await TAURI_INVOKE("process_list", { sort, limit });
},
async processKill(pid: number) : Promise<null> {
    return await TAURI_INVOKE("process_kill", { pid });
},
async fileSearch(query: string, limit: number | null) : Promise<FileHit[]> {
    return await TAURI_INVOKE("file_search", { query, limit });
},
/**
 * 手动触发全量重扫（后台线程，完成发 FileIndexUpdated 事件）
 */
async fileIndexRefresh() : Promise<null> {
    return await TAURI_INVOKE("file_index_refresh");
},
/**
 * 打开文件（须位于索引根目录内，SDD §8 白名单）
 */
async openPath(path: string) : Promise<null> {
    return await TAURI_INVOKE("open_path", { path });
},
/**
 * 在资源管理器中定位
 */
async revealInExplorer(path: string) : Promise<null> {
    return await TAURI_INVOKE("reveal_in_explorer", { path });
},
async desktopModeEnter() : Promise<null> {
    return await TAURI_INVOKE("desktop_mode_enter");
},
async desktopModeExit() : Promise<null> {
    return await TAURI_INVOKE("desktop_mode_exit");
},
async desktopModeIsActive() : Promise<boolean> {
    return await TAURI_INVOKE("desktop_mode_is_active");
},
/**
 * 唤出系统真实「开始」菜单（注入 Ctrl+Esc，见 hamster_platform::shell）
 */
async startMenuOpen() : Promise<null> {
    return await TAURI_INVOKE("start_menu_open");
},
async benchScanAgents() : Promise<AgentInfo[]> {
    return await TAURI_INVOKE("bench_scan_agents");
},
async benchListProjects() : Promise<string[]> {
    return await TAURI_INVOKE("bench_list_projects");
},
/**
 * 聚合各已安装 Agent 的历史工作目录（读会话记录的 cwd，Store 为空时的项目来源）。
 * 只保留磁盘上仍存在的目录，并跳过临时目录（e2e 沙箱会污染 ~/.claude/projects 等）。
 */
async benchAgentWorkspaces() : Promise<WorkspaceRecord[]> {
    return await TAURI_INVOKE("bench_agent_workspaces");
},
async benchStreamCreate(args: StreamCreateArgs) : Promise<LiveSessionInfo> {
    return await TAURI_INVOKE("bench_stream_create", { args });
},
async benchStreamSend(sessionId: string, text: string, model: string | null, effort: string | null) : Promise<null> {
    return await TAURI_INVOKE("bench_stream_send", { sessionId, text, model, effort });
},
async benchStreamInterrupt(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("bench_stream_interrupt", { sessionId });
},
async benchStreamKill(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("bench_stream_kill", { sessionId });
},
async benchListStreamSessions() : Promise<LiveSessionInfo[]> {
    return await TAURI_INVOKE("bench_list_stream_sessions");
},
/**
 * PTY 活会话（与流式列表并存；侧栏合并去重）
 */
async benchListLiveSessions() : Promise<LiveSessionInfo[]> {
    return await TAURI_INVOKE("bench_list_live_sessions");
},
/**
 * 创建 PTY 会话（官方 CLI TUI + 官方 resume 参数）。输出经 ipc Channel 推送；
 * GUI 输入框的文字走 bench_pty_send_prompt（bracketed-paste 注入 stdin）。
 */
async benchPtyCreate(args: PtyCreateArgs, onData: TAURI_CHANNEL<number[]>) : Promise<LiveSessionInfo> {
    return await TAURI_INVOKE("bench_pty_create", { args, onData });
},
async benchPtyWrite(sessionId: string, data: string) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_write", { sessionId, data });
},
/**
 * GUI 输入通道：文本以 bracketed-paste 注入运行中会话（混用模式，上游设计文档 runtime-design §3.6）
 */
async benchPtySendPrompt(sessionId: string, text: string) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_send_prompt", { sessionId, text });
},
async benchPtyResize(sessionId: string, cols: number, rows: number) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_resize", { sessionId, cols, rows });
},
async benchPtyKill(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("bench_pty_kill", { sessionId });
},
async benchListHistorySessions() : Promise<SessionSummary[]> {
    return await TAURI_INVOKE("bench_list_history_sessions");
},
/**
 * 检索前触发一轮快速增量摄取（未变更文件仅 stat + 游标比对，短暂阻塞可接受——
 * 与上游同款：async 命令体内直调 rusqlite，State 借用不跨 spawn）
 */
async benchSearchSessions(query: SearchQuery) : Promise<SearchHit[]> {
    return await TAURI_INVOKE("bench_search_sessions", { query });
},
async benchSessionMessages(agent: string, sessionKey: string, aroundSeq: number, window: number) : Promise<SnapshotMessage[]> {
    return await TAURI_INVOKE("bench_session_messages", { agent, sessionKey, aroundSeq, window });
},
async benchListSessionMessages(agent: string, sessionKey: string, fromSeq: number, limit: number) : Promise<SessionMessagesPage> {
    return await TAURI_INVOKE("bench_list_session_messages", { agent, sessionKey, fromSeq, limit });
},
/**
 * 某代理在项目下最新入索引的会话键（登记表条目缺 sessionKey 时的恢复回退）
 */
async benchLatestIndexedSession(agent: string, projectDir: string) : Promise<SessionSummary | null> {
    return await TAURI_INVOKE("bench_latest_indexed_session", { agent, projectDir });
},
async benchIndexStatus() : Promise<IndexStatus> {
    return await TAURI_INVOKE("bench_index_status");
},
async benchIndexRefresh() : Promise<IndexStatus> {
    return await TAURI_INVOKE("bench_index_refresh");
},
async benchReindex() : Promise<IndexStatus> {
    return await TAURI_INVOKE("bench_reindex");
},
/**
 * 删除一条历史会话：备份源文件（上游红线②，备份后删）→ 删除 → 清索引派生数据
 */
async benchSessionDelete(agent: string, sessionKey: string) : Promise<null> {
    return await TAURI_INVOKE("bench_session_delete", { agent, sessionKey });
},
/**
 * 创建桌面助手会话：解析默认代理 → 铸造令牌 → 注入 HTTP MCP 配置 → spawn。
 */
async benchAssistantCreate(args: AssistantCreateArgs) : Promise<AssistantSessionInfo> {
    return await TAURI_INVOKE("bench_assistant_create", { args });
},
/**
 * 各 agent 的桌面 MCP 分发状态
 */
async agentMcpStatus() : Promise<AgentMcpStatus[]> {
    return await TAURI_INVOKE("agent_mcp_status");
},
/**
 * 开/关某 agent 的桌面 MCP 分发：
 * 开 = 源 upsert（HTTP IR）+ target 启用 → plan/apply 写入其配置文件；
 * 关 = 源临时置 disabled → 仅对该 target apply（渲染省略 = 摘除条目）→ 恢复源。
 * Drift（基线外的既有配置）统一 Overwrite：render 本身「读现有→合并」，
 * 用户已有条目保留，apply 自动落备份可回滚。
 */
async agentMcpSetEnabled(agentId: string, enabled: boolean) : Promise<null> {
    return await TAURI_INVOKE("agent_mcp_set_enabled", { agentId, enabled });
},
/**
 * 接入信息（URL 含实际端口；端口回退时前端提示更新已分发配置）
 */
async agentMcpAccessInfo() : Promise<McpAccessInfo> {
    return await TAURI_INVOKE("agent_mcp_access_info");
},
/**
 * 扫描插件列表
 */
async pluginList() : Promise<PluginInfo[]> {
    return await TAURI_INVOKE("plugin_list");
},
/**
 * 读取插件入口代码（前端 blob 动态 import 用）
 */
async pluginReadCode(pluginId: string, entry: string) : Promise<string> {
    return await TAURI_INVOKE("plugin_read_code", { pluginId, entry });
},
/**
 * 插件私有存储读（settings 表 `plugin.<id>.<key>` 命名空间）
 */
async pluginStorageGet(pluginId: string, key: string) : Promise<string | null> {
    return await TAURI_INVOKE("plugin_storage_get", { pluginId, key });
},
/**
 * 插件私有存储写
 */
async pluginStorageSet(pluginId: string, key: string, value: string) : Promise<null> {
    return await TAURI_INVOKE("plugin_storage_set", { pluginId, key, value });
},
/**
 * 插件删除：整目录移除（防路径逃逸）
 */
async pluginDelete(pluginId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin_delete", { pluginId });
},
/**
 * 受控桥：插件经 manifest 声明的权限调用有限的桌面能力。
 * 返回 JSON 字符串（能力各自定义返回形态）。
 */
async pluginBridgeCall(pluginId: string, capability: string, payload: string) : Promise<string> {
    return await TAURI_INVOKE("plugin_bridge_call", { pluginId, capability, payload });
},
/**
 * 打开原生托盘溢出弹层（系统自带 UI，含全部后台托盘 app，可直接交互）。
 * 
 * 借壳显示系统任务栏的 ~1s 里先把 dock 切成不透明（见 [`OpaqueDockGuard`]），
 * 配合 open_overflow 内的置顶压制，全程看不到任务栏闪现，dock 不再「上浮」。
 */
async trayOpenOverflow() : Promise<null> {
    return await TAURI_INVOKE("tray_open_overflow");
},
/**
 * 检查更新：None = 已是最新；Some = 可升级到对应版本
 */
async updateCheck() : Promise<UpdateInfo | null> {
    return await TAURI_INVOKE("update_check");
},
/**
 * 下载并安装更新：进度经 UpdateProgress 事件推送（约 100ms 一帧节流）。
 * 完成后应用退出、由 NSIS 静默安装器接管（installMode=quiet）；若进程
 * 未被接管（非 Windows 行为兜底）则主动重启。
 */
async updateInstall() : Promise<null> {
    return await TAURI_INVOKE("update_install");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appIndexUpdated: AppIndexUpdated,
benchPtyExit: BenchPtyExit,
benchStreamEvent: BenchStreamEvent,
benchStreamExit: BenchStreamExit,
coreReady: CoreReady,
desktopModeChanged: DesktopModeChanged,
fileIndexUpdated: FileIndexUpdated,
focusFinished: FocusFinished,
focusTick: FocusTick,
todoReminder: TodoReminder,
updateProgress: UpdateProgress,
vaultLocked: VaultLocked
}>({
appIndexUpdated: "app-index-updated",
benchPtyExit: "bench-pty-exit",
benchStreamEvent: "bench-stream-event",
benchStreamExit: "bench-stream-exit",
coreReady: "core-ready",
desktopModeChanged: "desktop-mode-changed",
fileIndexUpdated: "file-index-updated",
focusFinished: "focus-finished",
focusTick: "focus-tick",
todoReminder: "todo-reminder",
updateProgress: "update-progress",
vaultLocked: "vault-locked"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Agent 域设置：桌面助手 persona、computer use 安全开关与桌面 MCP 分发
 */
export type Agent = { 
/**
 * computer use 总开关：允许 agent 经桌面 MCP server 操作真实鼠标键盘
 * （HAMSTER_CU_MODE 注入；默认关，安全红线见 docs/03 §3.4）
 */
computer_use_enabled: boolean; 
/**
 * 桌面助手 persona（追加为 agent system prompt；空 = 内置仓鼠默认）
 */
assistant_persona: string; 
/**
 * 桌面 MCP 端口（None = 默认 47613；被占用时回退随机端口，实际值见设置页）
 */
mcp_port: number | null; 
/**
 * 用户级长效令牌：写入各 agent 配置文件供外部 MCP 宿主接入
 * （None = 首启自动生成；区别于 bench 助手会话的一次性令牌）
 */
mcp_user_token: string | null; 
/**
 * 已开启桌面 MCP 分发的 agent id（写入其配置文件；移除 = 从配置摘除条目）
 */
mcp_agents: string[]; 
/**
 * 桌面助手默认代理（空 = 自动：claude → zcode → 首个已装且支持结构化通道）
 */
assistant_agent_id: string; 
/**
 * 桌面助手默认模型（空 = agent CLI 自身默认）
 */
assistant_model: string; 
/**
 * 桌面助手默认推理强度（空 = agent 默认；选项来自各 agent launchOptions）
 */
assistant_effort: string; 
/**
 * 用户手动指定的 Agent CLI 程序路径（agentId → 绝对路径）：优先于自动探测，
 * 供绿色版/自拷贝的 CLI 注册进应用。写入口 agent_cli_path_set（先校验再落库）
 */
cli_paths: Partial<{ [key in string]: string }> }
/**
 * 扫描结果（前端展示形态）。
 */
export type AgentInfo = { id: string; name: string; installed: boolean; version: string | null; 
/**
 * 配置根路径（未安装为 null）
 */
configRoot: string | null; 
/**
 * CLI 程序路径（自动探测 = 多版本择优；用户在设置里手动指定后为所填路径；
 * null = 未探测到）
 */
program: string | null; capabilities: Caps; 
/**
 * 支持内嵌对话（v2.0：adapter 提供 runtime 画像）
 */
chat: boolean; 
/**
 * 首条 prompt 注入方式；None = 不支持自动注入（消息不会随启动送达）
 */
promptInject: PromptInject | null; 
/**
 * 启动可选参数（模型/推理强度，官方 CLI 参数）；None = 不支持内嵌对话
 */
launchOptions: LaunchOptions | null; 
/**
 * 支持官方结构化流式通道（v2.0 R3：GUI 会话实时渲染）
 */
streaming: boolean }
/**
 * 分发状态（agent_mcp_status 返回项）
 */
export type AgentMcpStatus = { agentId: string; agentName: string; installed: boolean; 
/**
 * 该 agent 是否支持 MCP 配置分发
 */
mcpCapable: boolean; 
/**
 * 用户开关（settings.agent.mcp_agents）
 */
enabled: boolean; 
/**
 * 配置文件路径（mcp 不可用为空串）
 */
configPath: string }
export type Ai = { base_url: string; model: string; api_key: string | null }
export type AppEntry = { app_key: string; display_name: string; 
/**
 * 启动目标：.lnk 完整路径（ShellExecute 直接打开）
 */
exec_target: string; kind: string; 
/**
 * 图标 PNG 缓存路径（None = 前端用字母占位）
 */
icon_path: string | null }
export type AppError = { code: string; message: string }
export type AppHealth = { name: string; version: string }
export type AppIndexUpdated = { count: number }
/**
 * 一扇应用窗口（dock 悬停卡片行）
 */
export type AppWindowInfo = { 
/**
 * 窗口句柄数值（app_window_activate 目标）
 */
id: number; title: string; minimized: boolean; 
/**
 * 窗口图标 PNG 的 data URL（空串时前端回退应用图标/首字占位）
 */
png: string }
export type Appearance = { theme: string; accent: string; glass: string; font_scale: number }
/**
 * bench_assistant_create 参数包
 */
export type AssistantCreateArgs = { firstPrompt: string | null; model: string | null; 
/**
 * 推理强度（结构化通道原生支持；None = 用设置默认）
 */
effort: string | null; 
/**
 * 指定代理；缺省按 设置默认 → claude → zcode → 首个已装 顺序解析
 */
agentId: string | null; 
/**
 * 恢复记忆：传入上一次会话的 rollout 键（codex thread/resume、claude
 * --resume），MCP 注入照常生效；进程仍存活时按幂等裁决直接重挂
 */
resumeKey: string | null }
/**
 * 桌面助手会话信息（返回给前端；附注入摘要便于调试与展示）
 */
export type AssistantSessionInfo = { session: LiveSessionInfo; agentId: string; 
/**
 * 本会话是否注入了桌面 MCP server
 */
mcpInjected: boolean; 
/**
 * 本会话 computer use 是否放行（未放行时 computer_* 工具被 server 拒绝）
 */
computerUseEnabled: boolean }
export type Behavior = { autostart: boolean; start_minimized: boolean; language: string; 
/**
 * 桌面模式切换热键（tauri global-shortcut 格式，重启生效）
 */
desktop_mode_hotkey: string; 
/**
 * 启动即进入桌面模式（打开应用直接全屏工作台 + 底部 Dock）
 */
desktop_mode_on_launch: boolean }
/**
 * PTY 会话进程退出（TUI 会话）
 */
export type BenchPtyExit = { session_id: string; exit_code: number }
/**
 * 流式会话事件（GUI 对话数据源；payload 为 上游 归一化 StreamEvent）
 */
export type BenchStreamEvent = StreamEvent
/**
 * 流式会话进程退出（前端刷新活会话列表）
 */
export type BenchStreamExit = { session_id: string }
/**
 * Agent 能力声明。Adapter 必须如实声明，不夸大。
 */
export type Caps = { 
/**
 * 支持用户级 MCP 分发
 */
mcp: boolean; 
/**
 * 支持项目级 MCP（scope = Project）
 */
projectMcp: boolean; 
/**
 * 规则文件分发（M1）
 */
rules: boolean; 
/**
 * Skills 目录管理（M1）
 */
skills: boolean; 
/**
 * 工具颗粒度（v1.2）：支持把 disabledTools 分发为工具级权限规则
 */
toolGranularity: boolean }
export type ChatMessage = { role: string; content: string }
export type CoreReady = { version: string }
export type CountdownCustom = { id: number; title: string; target_date: string; emoji: string }
export type CountdownItem = { title: string; days: number; 
/**
 * auto = 内置计算项；custom = 用户自建
 */
kind: string; emoji: string }
export type CpuStat = { percent: number; core_count: number; name: string }
export type DesktopModeChanged = { active: boolean }
export type DiskStat = { 
/**
 * 挂载点，如 "C:\"
 */
mount: string; total_gb: number; used_gb: number; percent: number }
/**
 * 弹窗载荷（dock-menu 窗口渲染 + 定位所需；文案在弹窗内用 i18n 现算）
 */
export type DockMenuPayload = { 
/**
 * "menu" = 右键菜单；"hover" = 悬停窗口卡片；"split" = 分屏管理弹层
 */
kind: string; appKey: string; 
/**
 * 锚点 x（任务栏窗口内逻辑 px，用于水平居中弹窗）
 */
x: number; 
/**
 * 定制组项才显示「移除」（menu）
 */
removable: boolean; 
/**
 * 运行中才显示「关闭窗口」（menu）
 */
running: boolean; 
/**
 * 支持多开才显示「多开应用」（menu；单实例应用点了只会收敛回已有窗口）
 */
multi: boolean; 
/**
 * 桌面接管态才给分屏入口（menu 里显示「分屏添加/移出/已满」一行）
 */
splitAvailable: boolean; 
/**
 * 该应用已在分屏中 → 那一行换成「移出分屏」
 */
splitMember: boolean; 
/**
 * 分屏已满 4/4 且该应用不在其中 → 那一行显示为禁用的「分屏已满」
 */
splitFull: boolean; 
/**
 * kind=split：当前成员数（弹窗高度按行数算）
 */
splitCount: number; 
/**
 * 悬停卡片窗口清单（hover；menu/split 为空）
 */
windows: AppWindowInfo[] }
export type FileHit = { path: string; name: string; ext: string | null; kind: string; size: number; mtime: number }
export type FileIndex = { roots: string[]; max_files: number }
export type FileIndexUpdated = { count: number }
export type FocusDayStat = { 
/**
 * 本地日期 "2026-09-13"
 */
day: string; 
/**
 * 当日专注分钟（向下取整）
 */
minutes: number }
/**
 * 一轮计时结束（专注/休息完成，历史已落库）
 */
export type FocusFinished = { kind: string }
export type FocusStatus = { 
/**
 * focus = 专注 / break = 休息
 */
kind: string; total_secs: number; remaining_secs: number; paused: boolean; todo_id: number | null }
/**
 * 计时心跳（每秒）
 */
export type FocusTick = { kind: string; remaining_secs: number; paused: boolean }
/**
 * 生成选项（length 8..=64；至少启用一个字符类）
 */
export type GenOptions = { length: number; upper: boolean; lower: boolean; digits: boolean; symbols: boolean; exclude_ambiguous: boolean }
/**
 * 索引库状态（Settings / Doctor 展示）。
 */
export type IndexStatus = { sessions: number; messages: number; 
/**
 * 库文件体积（字节）
 */
bytes: number }
/**
 * 一个启动选项的声明（choices 供前端下拉，arg_template 是含 {v} 占位符的
 * 官方参数模板，可含多个 token，spawn 前按空格拆分）。
 */
export type LaunchOption = { choices: string[]; argTemplate: string; default: string | null; 
/**
 * 选择的值在 GUI 流式会话同样生效（claude 启动 flag / codex turn 参数）；
 * false = 仅 TUI 会话生效（如 opencode：TUI `--model`，其 ACP 通道
 * 无启动级模型参数、`session/set_config` 上游未实现）
 */
streamOverride: boolean }
/**
 * 前端可选的启动参数组合（供 AgentInfo 能力暴露）。
 */
export type LaunchOptions = { model: LaunchOption | null; effort: LaunchOption | null }
/**
 * 活会话信息（前端 Chat 左栏 / 上下文条的数据形态）。
 */
export type LiveSessionInfo = { 
/**
 * 上游 侧会话 id（uuid）
 */
sessionId: string; agentId: string; 
/**
 * 会话形态（Agent 对话 / 通用终端）；终端会话不进 Chat 侧栏
 */
kind: SessionKind; 
/**
 * 通道：PTY TUI 或结构化流式（原生视图据此分流数据源）
 */
channel: SessionChannel; projectDir: string; 
/**
 * 会话是否仍在运行（false 时 exit_code 有效）
 */
running: boolean; exitCode: number | null; 
/**
 * Unix 毫秒时间戳
 */
startedAt: number; 
/**
 * 最近一次输入/输出的时刻（用于排序）
 */
lastActiveAt: number; 
/**
 * rollout 会话键（resume 启动时记录）：侧栏按会话聚合 + spawn 幂等裁决
 */
resumeKey?: string | null }
/**
 * 接入信息（设置页展示 + 供手动复制到任意 MCP 宿主）
 */
export type McpAccessInfo = { url: string; token: string; port: number; 
/**
 * 端口回退过（首选端口被占用，分发出去的固定 URL 当前不可用）
 */
portFellBack: boolean; defaultPort: number }
export type MemStat = { total_gb: number; used_gb: number; percent: number }
export type Note = { id: number; content: string; pinned: boolean; updated_at: number }
/**
 * 插件信息（命令返回；不含代码）
 */
export type PluginInfo = { id: string; name: string; version: string; description: string; author: string; entry: string; 
/**
 * 声明式权限（透传给前端构建 ctx.api）
 */
permissions: string[]; 
/**
 * 入口文件完整路径（前端据此请求代码）
 */
entryPath: string }
export type ProcInfo = { pid: number; name: string; mem_mb: number; cpu: number }
/**
 * 首条 prompt 送达方式（runtime-design.md §3.4）。
 */
export type PromptInject = 
/**
 * 作为位置参数拼进启动 argv（`claude "消息"`）
 */
"argv" | 
/**
 * 先开终端，用户自己在 TUI 内输入（上游 不注入）
 */
"none"
/**
 * bench_pty_create 参数包（specta 的 SpectaFn 上限 10 参，命令参数打包）
 */
export type PtyCreateArgs = { agentId: string; projectDir: string; firstPrompt: string | null; model: string | null; effort: string | null; resumeKey: string | null; cols: number; rows: number }
export type Search = { hotkey: string; search_apps: boolean; search_files: boolean }
/**
 * 一条全文命中（消息级定位）。
 */
export type SearchHit = { agent: string; sessionKey: string; seq: number; sessionTitle: string; projectPath: string | null; at: number | null; 
/**
 * 命中上下文片段（带标记）
 */
snippet: string }
/**
 * 全文检索查询（agents 为空 = 不过滤）。
 */
export type SearchQuery = { text: string; agents: string[]; project: string | null; limit: number | null }
/**
 * 会话通道形态：PTY 内嵌 TUI，或官方结构化协议流式（v2.0 R3）。
 */
export type SessionChannel = "pty" | "stream"
/**
 * 会话形态：Agent TUI 对话（Chat 域主体）或工作台通用终端（底部 dock，
 * git/构建等日常 shell，不属于任何 Agent）。
 */
export type SessionKind = "agent" | "terminal"
/**
 * 原生视图分页：会话消息总数 + 从 from_seq 起的升序消息。
 */
export type SessionMessagesPage = { total: number; messages: SnapshotMessage[] }
/**
 * 一条历史会话的摘要（从 Agent 官方落盘文件只读提取）。
 */
export type SessionSummary = { 
/**
 * Agent 全小写 id（"claude" / "codex" / …）
 */
agent: string; 
/**
 * Agent 侧会话标识（resume 用，如 Claude 的 uuid）
 */
sessionKey: string; 
/**
 * 会话所属项目目录（Agent 落盘的 cwd）
 */
projectPath: string; 
/**
 * 标题（首条用户消息截断；提取不到时为空，由前端兜底）
 */
title: string; 
/**
 * 最近活跃时刻（Unix 毫秒，取文件 mtime）
 */
lastActiveAt: number; 
/**
 * 源文件路径（只读回指，调试与排重用）
 */
sourcePath: string; 
/**
 * 是否已声明官方 resume 参数（false = 仅浏览，UI 不提供续聊）
 */
resumable: boolean; 
/**
 * 续聊须走 TUI（PTY）通道：GUI 流式协议 resume 该会话必失败
 * （如 codex rollout 引用当前配置无法解析的 model provider，实测 0.152.0）
 */
resumeViaTui?: boolean }
export type Settings = { appearance: Appearance; search: Search; file_index: FileIndex; weather: Weather; ai: Ai; behavior: Behavior; 
/**
 * Agent 域（桌面助手 / computer use，M4）
 */
agent: Agent }
/**
 * 一条可检索的消息投影（原文仍在 Agent 源文件，索引只存文本投影）。
 */
export type SnapshotMessage = { 
/**
 * 所在源文件的行号（0 基），作为会话内稳定序号
 */
seq: number; role: SnapshotRole; 
/**
 * 提取的纯文本（搜索面）
 */
text: string; toolName: string | null; at: number | null }
/**
 * 消息角色（索引投影用，保持最小集合）。
 */
export type SnapshotRole = "user" | "assistant" | 
/**
 * 思考/推理内容（默认折叠展示）
 */
"thinking" | "tool" | "system"
/**
 * 一扇被托管的窗口（对外快照）
 */
export type SplitMember = { 
/**
 * 窗口句柄数值（退出/移出/关闭都用它）
 */
windowId: number; 
/**
 * 来源应用（菜单据此判断「该应用是否已在分屏里」）
 */
appKey: string; 
/**
 * 窗口标题（列表主文案；多开的应用靠它区分）
 */
title: string; 
/**
 * 进程名（标题为空时的兜底文案）
 */
process: string; 
/**
 * 窗口图标 PNG 的 data URL（空串时前端回退首字占位）
 */
png: string; 
/**
 * 0 起的格序（UI 显示时 +1）
 */
slot: number }
/**
 * 分屏会话快照（`active=false` 时其余字段为空值）
 */
export type SplitState = { active: boolean; 
/**
 * 布局 id（`tile::TileLayout::id`）；空串 = 无会话
 */
layout: string; 
/**
 * 布局格数（空位数 = slots − members.len()）
 */
slots: number; 
/**
 * 上限（= 4）
 */
capacity: number; members: SplitMember[] }
/**
 * 创建流式会话（官方 headless 协议）。事件经 BenchStreamEvent 推送；
 * first_prompt 非空时握手后立即发起首轮。
 * bench_stream_create 参数包（specta 的 SpectaFn 上限 10 参，命令参数打包）
 */
export type StreamCreateArgs = { agentId: string; projectDir: string; firstPrompt: string | null; model: string | null; effort: string | null; resumeKey: string | null; fork: boolean }
/**
 * 归一化流式事件（方言无关；前端据此增量渲染原生视图）。
 */
export type StreamEvent = { sessionId: string; 
/**
 * 方言侧条目 id（增量拼接的去重键；无条目语义的事件为空）
 */
itemId: string; at: number; kind: StreamEventKind; 
/**
 * 文本增量 / 条目全文（按 kind 语义）
 */
text: string; 
/**
 * 工具类条目的名称（command 首词 / server.tool）
 */
toolName: string | null; 
/**
 * 工具条目状态（completed/failed/inProgress…，方言原样透传）
 */
status: string | null; 
/**
 * 结构化文件修改（仅 ToolItem 且方言提供时；前端渲染 diff 卡片）
 */
diff?: StreamEventDiff | null }
/**
 * 工具条目的结构化 diff（ACP `tool_call` 的 `content[].type=diff`；其余方言/情形为 None）。
 */
export type StreamEventDiff = { path: string; oldText: string | null; newText: string }
export type StreamEventKind = 
/**
 * 用户消息回显（权威全文）
 */
"userEcho" | 
/**
 * 助手消息增量（append）
 */
"agentDelta" | 
/**
 * 助手消息完成（权威全文，替换该条目）
 */
"agentDone" | 
/**
 * 思考增量（append）
 */
"reasoningDelta" | 
/**
 * 条目完成：工具调用（command/fileChange/mcpToolCall…）
 */
"toolItem" | 
/**
 * 条目完成：思考全文
 */
"reasoningDone" | 
/**
 * 轮次开始（输入已被接受）
 */
"turnStarted" | 
/**
 * 轮次完成（running=false）
 */
"turnCompleted" | 
/**
 * 协议错误 / 会话错误
 */
"error" | 
/**
 * 通道进程退出
 */
"exit"
export type SystemSnapshot = { mem: MemStat; disks: DiskStat[]; cpu: CpuStat; 
/**
 * Windows 上常为空（依赖传感器驱动），前端按空隐藏
 */
temps: TempStat[] }
export type TempStat = { label: string; celsius: number }
export type Todo = { id: number; content: string; done: boolean; created_at: number; 
/**
 * 截止时刻（NULL = 无；日期任务取当日 00:00）
 */
due_at: number | null; 
/**
 * 提醒时刻（NULL = 不提醒）
 */
remind_at: number | null; 
/**
 * 已提醒时刻（NULL = 未提醒）
 */
reminded_at: number | null; 
/**
 * 循环规则（core::recur::RULES；NULL = 不循环）
 */
recur: string | null }
/**
 * 待办提醒到点（系统通知已同时发出）
 */
export type TodoReminder = { id: number; content: string; due_at: number | null }
/**
 * 可用更新摘要（version 为目标版本；notes 为 release 正文，仅展示用）
 */
export type UpdateInfo = { version: string; notes: string | null }
/**
 * 更新下载进度（done=true 表示安装包已就绪，应用即将退出交由安装器接管）
 */
export type UpdateProgress = { downloaded: number; total: number | null; done: boolean }
/**
 * 条目元数据（列表用，不含敏感字段）
 */
export type VaultItem = { id: number; title: string; username: string; url: string; favorite: boolean; created_at: number; updated_at: number; password_updated_at: number }
/**
 * 新建/编辑入参（明文经 IPC 传入，store 层立即加密落库）
 */
export type VaultItemInput = { title: string; username: string; url: string; password: string; notes: string; favorite: boolean }
/**
 * 密码箱已锁定（reason: manual | idle）
 */
export type VaultLocked = { reason: string }
/**
 * 敏感字段（信封内的 JSON 明文结构）
 */
export type VaultSecret = { password: string; notes: string }
/**
 * 密码箱总览状态（页面三态：未初始化 / 已锁 / 已解锁）
 */
export type VaultStatus = { initialized: boolean; unlocked: boolean; hint: string | null; auto_lock_secs: number }
export type VolumeState = { 
/**
 * 0.0 - 1.0
 */
level: number; muted: boolean }
export type Weather = { provider: string; city_id: string; qweather_key: string | null }
export type WeatherNow = { city: string; temp: number; kind: string; emoji: string; temp_min: number; temp_max: number; 
/**
 * 缓存时间（unix 秒）；0 = 实时
 */
fetched_at: number }
/**
 * 一条 workspace 记录。
 */
export type WorkspaceRecord = { dir: string; 
/**
 * 发现来源描述（展示用），如 "claude projects" / "codex sessions" / "zcode recentProjects"
 */
source: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
